# Generated by Django 2.2.7 on 2022-06-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamic', '0002_auto_20220624_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='评论内容')),
                ('status', models.IntegerField(default=1, verbose_name='1可用0不可用')),
                ('pid', models.IntegerField(default=0, verbose_name='父id')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.Dynamic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
