# Generated by Django 2.2.7 on 2022-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220620_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
