# Generated by Django 2.2.7 on 2022-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_integral'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='autograph',
            field=models.CharField(default=1, max_length=255, verbose_name='个性签名'),
            preserve_default=False,
        ),
    ]
