# Generated by Django 2.2.7 on 2022-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_autograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='autograph',
        ),
        migrations.AddField(
            model_name='user',
            name='autograph',
            field=models.CharField(default=1, max_length=255, verbose_name='个性签名'),
            preserve_default=False,
        ),
    ]
