# Generated by Django 2.2.7 on 2022-06-27 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220626_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='昵称')),
                ('image', models.CharField(max_length=256, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')])),
                ('autograph', models.CharField(max_length=255, verbose_name='个性签名')),
                ('birthday', models.DateTimeField(verbose_name='出生日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
