# Generated by Django 2.2.2 on 2022-07-12 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用户姓名')),
                ('card_id', models.CharField(max_length=18, verbose_name='身份证号')),
                ('bank_card_id', models.CharField(max_length=100, verbose_name='银行卡号')),
                ('password', models.CharField(max_length=6, verbose_name='用户银行卡密码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开户时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联账号')),
            ],
            options={
                'db_table': 'bank_bankuser',
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_money', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='贷款金额')),
                ('loan_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='贷款时间')),
                ('late_time', models.DateTimeField( verbose_name='最晚还款贷款时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser', verbose_name='关联用户')),
            ],
            options={
                'db_table': 'bank_loanrecord',
            },
        ),
    ]
