# Generated by Django 2.2.2 on 2022-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='cause',
            field=models.TextField(default='', verbose_name='不通过原因'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='content',
            field=models.IntegerField(default=0, verbose_name='第N次借款'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='expect',
            field=models.IntegerField(default=0, verbose_name='分期'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态0通过/   1不通过'),
        ),
    ]
