# Generated by Django 2.2.2 on 2022-07-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20220713_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='loan_money',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='贷款金额'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser', verbose_name='关联开户人员'),
        ),
    ]
