# Generated by Django 2.2.2 on 2022-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20220713_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='late_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最晚还款贷款时间'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='loan_money',
            field=models.FloatField(verbose_name='贷款金额'),
        ),
    ]
