# Generated by Django 2.2.2 on 2022-07-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20220713_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='check_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='审核人id'),
        ),
    ]
