# Generated by Django 2.2.2 on 2022-07-15 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_loanrecord_check_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='money',
            field=models.IntegerField(default=0, verbose_name='余额'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='loan_status',
            field=models.IntegerField(default=0, verbose_name='状态(0未审核/ 1筹备中/   2满标/)'),
        ),
        migrations.CreateModel(
            name='TopUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='充值金额')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='充值时间')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态(0成功/ 1网络错误/   2取消/)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser', verbose_name='充值人员')),
            ],
            options={
                'db_table': 'bank_topuprecord',
            },
        ),
    ]
