# Generated by Django 2.2.2 on 2022-07-18 21:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20220715_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='have_money',
            field=models.IntegerField(blank=True, null=True, verbose_name='已投资金额'),
        ),
        migrations.CreateModel(
            name='InvestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_money', models.IntegerField(blank=True, null=True, verbose_name='投资金额')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开户时间')),
                ('earnings_money', models.IntegerField(blank=True, null=True, verbose_name='预收益')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.LoanRecord', verbose_name='贷款理财')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser', verbose_name='关联开户人员')),
            ],
            options={
                'db_table': 'bank_investrecord',
            },
        ),
    ]
