# Generated by Django 2.2.2 on 2022-07-19 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20220718_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='investrecord',
            name='status',
            field=models.IntegerField(default=0, verbose_name='0抢购1投资成功2已放款'),
        ),
        migrations.AlterField(
            model_name='investrecord',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投资时间'),
        ),
        migrations.AlterField(
            model_name='investrecord',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.LoanRecord', verbose_name='理财'),
        ),
    ]
