# Generated by Django 2.2.2 on 2022-07-19 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0012_auto_20220719_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_url', models.CharField(max_length=256, verbose_name='前面身份证')),
                ('reverseside_url', models.CharField(max_length=256, verbose_name='反面身份证')),
                ('status', models.IntegerField(default=0, verbose_name='状态(0未审核/ 1通过/    2不通过)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='开户人员')),
            ],
            options={
                'db_table': 'bank_card',
            },
        ),
    ]
