# Generated by Django 2.2.2 on 2022-07-19 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_amount', models.IntegerField(default=0, verbose_name='还款金额')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='还款时间')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser', verbose_name='还款人')),
            ],
            options={
                'db_table': 'bank_pay_record',
            },
        ),
    ]
