# Generated by Django 2.2.2 on 2022-07-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_repaymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='repayment_money',
            field=models.IntegerField(default=0, verbose_name='已投资金额'),
        ),
    ]
