# Generated by Django 2.2.2 on 2022-06-30 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integral_shopping', '0002_pointsmall_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='积分兑换记录时间')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户id')),
                ('goods_id', models.IntegerField(default=0, verbose_name='商品id')),
                ('price', models.IntegerField(default=0, verbose_name='积分')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
            ],
            options={
                'db_table': 'integral_shopping_record',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='类型名')),
            ],
            options={
                'db_table': 'integral_shopping_type',
            },
        ),
        migrations.AddField(
            model_name='pointsmall',
            name='cateid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integral_shopping.Type', verbose_name='商品类别'),
        ),
    ]
