# Generated by Django 2.2.2 on 2022-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integral_shopping', '0003_auto_20220630_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='来源说明'),
        ),
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.IntegerField(blank=True, null=True, verbose_name='0是减少积分/    1添加积分'),
        ),
        migrations.AlterField(
            model_name='record',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='goods_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='record',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='用户id'),
        ),
    ]
