# Generated by Django 2.2.2 on 2022-07-04 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=1, verbose_name='签到的天数')),
                ('reward_coin', models.IntegerField(default=0, verbose_name='奖励积分数量')),
                ('extra_reward', models.IntegerField(default=0, verbose_name='额外积分奖励')),
            ],
            options={
                'db_table': 'sign_in_reward',
            },
        ),
        migrations.CreateModel(
            name='DailySignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_days', models.IntegerField(default=0, verbose_name='累计签到天数')),
                ('continuous_day', models.IntegerField(default=0, verbose_name='连续签到天数')),
                ('sign_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='签到用户')),
            ],
            options={
                'db_table': 'sign_in_daily',
            },
        ),
    ]
