# Generated by Django 2.2.7 on 2022-06-29 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品描述')),
                ('image', models.CharField(blank=True, max_length=300, null=True, verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField(default=0, verbose_name='库存数量')),
                ('lock_count', models.IntegerField(default=0, verbose_name='锁定数量')),
                ('sale_count', models.IntegerField(default=0, verbose_name='已售数量')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(default='', max_length=256, verbose_name='图片地址')),
                ('moments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品id')),
            ],
            options={
                'db_table': 'goods_picture',
            },
        ),
    ]
