# Generated by Django 2.2.7 on 2022-06-29 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='moments',
            new_name='goods',
        ),
    ]
