# Generated by Django 2.2.7 on 2022-06-29 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20220629_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='lock_count',
            field=models.IntegerField(default=0, verbose_name=' 锁定数量'),
        ),
        migrations.CreateModel(
            name='GoodsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='积分兑换记录时间')),
                ('price', models.IntegerField(default=0, verbose_name='积分')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商品id')),
            ],
            options={
                'db_table': 'goods_record',
            },
        ),
    ]
