# Generated by Django 2.2.2 on 2022-07-25 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100, verbose_name='第N期问卷调查   /1.1')),
                ('count', models.TextField(verbose_name='题目内容')),
                ('status', models.IntegerField(default=0, verbose_name='状态0存在/   1删除')),
                ('type', models.IntegerField(default=-1, verbose_name='类型0单选|     1多选|    2判断|    3问答|')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_wrong', models.BooleanField(blank=True, null=True, verbose_name='对错')),
                ('answer_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='选项类型/ A/B/C')),
                ('answer_content', models.CharField(max_length=168, verbose_name='选项内容')),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='问题id')),
            ],
            options={
                'db_table': 'survey_answer',
            },
        ),
    ]
