# Generated by Django 2.2.2 on 2022-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=68, verbose_name='第N期问卷调查   /1.1'),
        ),
    ]
