# Generated by Django 2.2.2 on 2022-07-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20220725_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='right_wrong',
            field=models.BooleanField(default=True, verbose_name='对错'),
        ),
    ]
