# Generated by Django 2.2.2 on 2022-06-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='pid',
            field=models.IntegerField(default=0, verbose_name='子id'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=168, null=True, verbose_name='角色资源地址'),
        ),
    ]
