# Generated by Django 2.2.2 on 2022-06-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_auto_20220627_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='出生日期'),
        ),
    ]
