# Generated by Django 2.2.2 on 2022-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0004_auto_20220628_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('friend_id', models.IntegerField(null=True, verbose_name='好友id')),
                # ('friend_name', models.CharField(max_length=10, verbose_name='好友名字')),
                ('status', models.IntegerField(default=1, verbose_name='状态(1黑名单2移除黑名单)')),
            ],
            options={
                'db_table': 'child_blacklist',
            },
        ),
    ]
