# Generated by Django 2.2.2 on 2022-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
