# Generated by Django 2.2.2 on 2022-07-08 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_auto_20220708_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='朋友id'),
        ),
    ]
