# Generated by Django 2.2.2 on 2022-07-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0008_blacklist_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='0好友1黑名单'),
        ),
    ]
