# Generated by Django 2.2.2 on 2022-07-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_letter', '0001_initial'),
        ('child', '0009_friends_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='handle_status',
            field=models.IntegerField(default=-1, verbose_name='是否添加为好友(0:同意,1:忽略,2:拒绝)'),
        ),
        migrations.AddField(
            model_name='friends',
            name='site_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_letter.SendAddFriendMail', verbose_name='站内信id'),
        ),
    ]
