# Generated by Django 2.2.2 on 2022-07-12 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0010_auto_20220710_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('friend_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_id', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'chat_record',
            },
        ),
    ]
