# Generated by Django 2.2.2 on 2022-07-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='0代表全部人，user_id普通用户')),
                ('content', models.CharField(max_length=256, verbose_name='信息内容')),
                ('title', models.CharField(max_length=20, verbose_name='信息标题')),
                ('content_id', models.IntegerField(verbose_name='消息内容，MailInfo中保存')),
                ('site_mail_type', models.IntegerField(verbose_name='站内信消息类型（0全体/用户id）')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name_plural': '发送站内信息',
                'db_table': 'site_letter_sendmail',
            },
        ),
        migrations.CreateModel(
            name='SendAddFriendMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='信息内容')),
                ('title', models.CharField(max_length=20, verbose_name='信息标题')),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('friend_id', models.IntegerField(verbose_name='请求人id')),
                ('status', models.IntegerField(default=0, verbose_name='处理结果(0:未处理,1:已处理)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='站内信消息user_id')),
            ],
            options={
                'verbose_name_plural': '发送添加好友站内信息',
                'db_table': 'site_letter_send_addfriendmail',
            },
        ),
        migrations.CreateModel(
            name='MailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='用户id')),
                ('status', models.IntegerField(default=0, verbose_name='0未读1已读')),
                ('send_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_letter.SendMail', verbose_name='站内信消息id')),
            ],
            options={
                'verbose_name_plural': '站内信息内容',
                'db_table': 'site_letter_mailinfo',
            },
        ),
    ]
