# Generated by Django 2.2.2 on 2022-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_letter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinfo',
            options={'verbose_name_plural': '站内状态'},
        ),
        migrations.RemoveField(
            model_name='sendmail',
            name='content_id',
        ),
        migrations.AddField(
            model_name='sendmail',
            name='status',
            field=models.IntegerField(default=1, verbose_name='0已读1未读'),
        ),
    ]
