# Generated by Django 2.2.2 on 2022-06-27 02:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatMoments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=268, verbose_name='朋友圈内容')),
                ('begin', models.DateTimeField(default=datetime.datetime(2022, 6, 27, 2, 56, 51, 440333, tzinfo=utc), verbose_name='发布时间')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'db_table': 'f_circle_wechatmoments',
            },
        ),
        migrations.CreateModel(
            name='WeChatPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=168, verbose_name='图片路径')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 6, 27, 2, 56, 51, 441332, tzinfo=utc), verbose_name='创建时间')),
                ('moment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_circle.WeChatMoments', verbose_name='朋友圈id')),
            ],
            options={
                'db_table': 'f_circle_wechatpicture',
            },
        ),
        migrations.CreateModel(
            name='WeChatComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=168, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2022, 6, 27, 2, 56, 51, 441332, tzinfo=utc), verbose_name='评论时间')),
                ('drop_time', models.DateTimeField(blank=True, null=True, verbose_name='评论时间')),
                ('start', models.IntegerField(blank=True, default=0, null=True, verbose_name='状态0显示/    1删除')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='父id')),
                ('moment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_circle.WeChatMoments', verbose_name='朋友圈id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'db_table': 'f_circle_wechatcomment',
            },
        ),
    ]
