# Generated by Django 2.2.2 on 2022-07-03 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('f_circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatcomment',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='wechatmoments',
            name='begin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='wechatpicture',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
