# Generated by Django 2.2.7 on 2022-06-24 05:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2022, 6, 24, 5, 4, 37, 583848, tzinfo=utc), verbose_name='发布时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('status', models.IntegerField(default=0, verbose_name='状态  0 审核中 1审核通过 2审核不通过')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='公告发布人')),
            ],
            options={
                'db_table': 'dynamic',
            },
        ),
    ]
