# Generated by Django 2.2.7 on 2022-06-24 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 15, 18, 22, 755107, tzinfo=utc), verbose_name='发布时间'),
        ),
    ]
