# Generated by Django 2.2.7 on 2022-06-25 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_auto_20220624_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 11, 12, 53, 466450, tzinfo=utc), verbose_name='发布时间'),
        ),
    ]
